### ISSUE TITLE
[FEATURE Request] Theme colour change with album art

### ISSUE THREAD

**Issue by HalfBloodprinc3** [AkaneTan/Symphonica#10]
Can you guys implement the feature, which changes the app theme colour when the song cover art/album art changed.

**Comment by AkaneTan** [comment]
Wait.. I don't think you can achieve this target without adding any external library or implanting an internal material engine. Symphonica is supposed to keep that away since it's designed to be implanted in system. I'll close this temporarily and reopen if any discoveries were found.

**Comment by HalfBloodprinc3** [comment]
> Wait.. I don't think you can achieve this target without adding any external library or implanting an internal material engine. Symphonica is supposed to keep that away since it's designed to be implanted in system. I'll close this temporarily and reopen if any discoveries were found.

Okay..
Thanks 😊

**Comment by AkaneTan** [comment]
Reopening this because many users requested. :) I'm thinking about a possible solution using pallette's coloring.

**Comment by AkaneTan** [comment]
Closed since symphonica will be archived soon. See https://github.com/AkaneTan/Symphonica/issues/15#issuecomment-1692267042 as a reference.
