### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by EisregenHaha** [AkaneTan/Symphonica#11]
Aight so this may be weird to open an issue here so i apologize in advance, but what happened to telegram account 🤔🤔 is luminarica ded now cuz you are effectively not even in the group now

P.s very cool player

**Comment by kreiorogit** [comment]
@EisregenHaha e

**Comment by EisregenHaha** [comment]
> @EisregenHaha e

Uh

**Comment by Wahid7852** [comment]
@EisregenHaha

**Comment by Wahid7852** [comment]
@Wahid7852 Wtf?

**Comment by Wahid7852** [comment]
It is better to ask this to Akane in telegram rather than opening an issue in a a completely irreverent repository.

I'll close it

**Comment by EisregenHaha** [comment]
> It is better to ask this to Akane in telegram rather than opening an issue in a a completely irreverent repository.
> 
> I'll close it

Thats the thing, i didnt have any access to telegram as its literally deleted lol

**Comment by nift4** [comment]
https://t.me/AkaneTan

**Comment by AkaneTan** [comment]
@EisregenHaha No actually

**Comment by AkaneTan** [comment]
@AkaneTan Issue templates are there for a reason
