### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [AkaneTan/Symphonica#8]
Can you please make sure to increase `versionCode` whenever you make a new release? As it currently stands, it's always set to `1`:

    package: name='org.akanework.symphonica' versionCode='1' versionName='0.56b.hotfix'

`versionCode` is what Android uses internally to tell versions apart and to know if some APK is considered to be an update.

Thanks in advance!

**Comment by AkaneTan** [comment]
Oh... okay. Haven't notice that yet 😢 Thank you for pointing out!!

**Comment by IzzySoft** [comment]
Just noticed that my updater complained, so I thought to let you know. For some background, and as a side-effect solving another riddle for you: [please see here](https://apt.izzysoft.de/packages/org.akanework.symphonica/) :wink:

**Comment by AkaneTan** [comment]
> Just noticed that my updater complained, so I thought to let you know. For some background, and as a side-effect solving another riddle for you: [please see here](https://apt.izzysoft.de/packages/org.akanework.symphonica/) 😉

Hi I'm writing this because I'm wondering how I can update symphonica for izzyondroid? It seems to stuck at version 0.57b for a while 🫠

**Comment by AkaneTan** [comment]
@AkaneTan Ah 0.58

**Comment by IzzySoft** [comment]
Well, by your tag names it is up to date: 0.58 > 0.6 :see_no_evil: Picked 0.6.0 manually now (should show up with the next sync around 6 pm UTC). As long as your tag naming stays consistent, it should work automatically and pull your new releases within 24h of your tagging and attaching an APK. But as shown, it uses [semantic versioning](https://semver.org/) to see if there's a newer release :wink: I can disable that and have it simply compare by time if needed, though.

**Comment by IzzySoft** [comment]
PS: Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to your app at IzzyOnDroid e.g. from your Readme :smiley:

**Comment by AkaneTan** [comment]
@IzzySoft Already added 😆

**Comment by IzzySoft** [comment]
Yay, thanks!
