### ISSUE TITLE
[FEATURE REQUEST] Waved progress bar

### ISSUE THREAD

**Issue by HalfBloodprinc3** [AkaneTan/Symphonica#9]

**Comment by AkaneTan** [comment]
Please add a tag in front of your issue like [FEATURE REQUEST] please.

**Comment by HalfBloodprinc3** [comment]
> Please add a tag in front of your issue like [FEATURE REQUEST] please.

Sorry about that.
But, could you please add that feature.

**Comment by AkaneTan** [comment]
> > Please add a tag in front of your issue like [FEATURE REQUEST] please.
> 
> Sorry about that. But, could you please add that feature.

Will do tonight.
Implementation already completed.

https://github.com/AkaneTan/Symphonica/assets/69606737/f5095f6b-5b69-46e6-b5f4-1c5d9aceb54a

**Comment by AkaneTan** [comment]
![Screenshot_2023-07-11-02-46-17-474_org akanework symphonica](https://github.com/AkaneTan/Symphonica/assets/69606737/503c09ca-9e74-414d-8974-d3ac235245c5)
Marking this as closed. Already included in source.

**Comment by AkaneTan** [comment]
But do notice that this feature isn't stable yet :(

**Comment by HalfBloodprinc3** [comment]
> But do notice that this feature isn't stable yet :(

Okay...
But thanks for this.❤️

Btw... I checked the release...it is empty!

**Comment by AkaneTan** [comment]
> > But do notice that this feature isn't stable yet :(
> 
> Okay... But thanks for this.❤️
> 
> Btw... I checked the release...it is empty!

It's in the latest commit and I haven't made a release about that yet.
https://github.com/AkaneTan/Symphonica/commit/0c116bbfca84d53e979e1d77bfeb7e68c6aa1e67

**Comment by HalfBloodprinc3** [comment]
> > > But do notice that this feature isn't stable yet :(
> > 
> > Okay... But thanks for this.❤️
> > 
> > Btw... I checked the release...it is empty!
> 
> It's in the latest commit and I haven't made a release about that yet.
> https://github.com/AkaneTan/Symphonica/commit/0c116bbfca84d53e979e1d77bfeb7e68c6aa1e67

Ooh ..okay...
Thanks buds😊
